apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-argo-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/asokjp/agrocd-sample.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc    
syncPolicy:
  syncOptions
  - CreateNamespace=true
  automated:
    selfHeal: true
    prune: true